### ISSUE TITLE
TvPower does not work

### ISSUE THREAD

**Issue by stevstrong** [avinash311/sony-tv-remote#1]
Hi,
I successfuly tested some commands with my Bravia TV.
The only problem I have that none of the "TvPower" nor "WakeUp" can turn on the TV.
I get the message:
`Failed TvPower AAAAAQAAAAEAAAAVAw== (Status 0): http://192.168.100.57/sony/IRCC Key: bravia_net (Response: "")`
After I turn on the TV with the original remote, I can send some commands with this tool and they are recognized by the TV (especially "Netflix" is very useful :)
Can you tell me what can I do, which command should I use to turn the TV on?

I can also turn on the TV with an app on my mobile phone (Android) so I think the TV is reachable over the net.

**Comment by avinash311** [comment]
On the `Help` tab, at the bottom, are some links that may help debug it - maybe your TV uses a different command?

Click on the `Get TV Remote Controller Info`  button for info on all commands your TV accepts. You may have to use your remote to turn it on first.

**Comment by stevstrong** [comment]
I get similar codes as listed here: https://pro-bravia.sony.net/develop/integrate/ircc-ip/ircc-codes/
But I have found out that in stand-by mode you cannot send any commands, you first have to wake up the device over LAN.
WOL is the keyword, and its need is specified here: (see last paragraph on the bottom of the page): https://pro-bravia.sony.net/develop/integrate/ip-control/index.html.
So you have to send first a WOL command and only after then you can send any IRCC command.
Obviously the Android app does this.
I have searched the net to find out whether WOL could be integrated into HTML script, but the result was negative.
I finally used a small EXE file on windows to wake up the device, then sending the IRCC commands was successful.

**Comment by avinash311** [comment]
Thanks, I'll add that info to the help section.

I tested with a regular Bravia TV, and it does not have that "Wake on LAN" setting. That is why it works, I expect.
Bravia Professional Displays may not work unless they have some way to always stay awake on Standby.

**Comment by stevstrong** [comment]
Just to clarify, I also have  Bravia TV, and I also do not have WOL setting. But I set it to eco (low power) mode, which means that the TV goes into standby after each power off command and consumes only (~3W). That is why I need to wake it up. Without the eco mode I assume it would work for me, too.
